### ISSUE TITLE
APPIMAGE_ROOT_DIR

### ISSUE THREAD

**Issue by probonopd** [epl-viz/EPL-Viz#1]
In case `APPIMAGE_ROOT_DIR` is related to [AppImage](http://appimage.org/), then you can use the existing environment variables:
* `APPDIR` - the directory in which the `AppRun` file resides
* `APPIMAGE` - the directory in which the `*.AppImage` file resides

These are automatically set for you when running an AppImage.

**Comment by mensinda** [comment]
Ok, thanks. Changed it to `APPDIR`

**Comment by probonopd** [comment]
But make sure that this does not break when the user extracts the content of the AppImage and runs AppRun directly.
